### ISSUE TITLE
Could this be published to the Chrome app store?

### ISSUE THREAD

**Issue by abourget** [EOSIO/eosio-reference-chrome-extension-authenticator-app#24]

**Comment by TaraTritt** [comment]
This repository has been released under [EOSIO Labs](https://github.com/EOSIO/eosio-reference-chrome-extension-authenticator-app#about-eosio-labs-). It is only intended to be an experimental reference implementation and not a proprietary product for uploading to the Chrome app store

**Comment by TaraTritt** [comment]
More information on this implementation is also available [here](https://medium.com/eosio/eosio-labs-release-ios-and-chrome-extension-authenticator-reference-applications-d5cf900f7b00)
